### ISSUE TITLE
Image array attaches to random board

### ISSUE THREAD

**Issue by daynewright** [nss-day-cohort-15/pinterest-d15-team-winterest#13]
I have the images loading on to the DOM, but the board it attaches to each time changes.  Might be some kind of async issue with the array being created. 

[BRANCH](https://github.com/nss-day-cohort-15/pinterest-d15-team-winterest/tree/mh-pleaseKillThis)

**Comment by matthamil** [comment]
Interesting. Looking at it now.

**Comment by matthamil** [comment]
Fixed. See PR https://github.com/nss-day-cohort-15/pinterest-d15-team-winterest/pull/14
